services:
  identity.provider:
    image: identity.provider
    build:
      context: .
      dockerfile: Identity.Provider/Dockerfile

  provider:
    image: provider
    build:
      context: .
      dockerfile: Provider/Dockerfile

  identity.admin:
    image: identity.admin
    build:
      context: .
      dockerfile: Apps/Identity.Admin/Dockerfile

  identity.admin-1:
    image: identity.admin-1
    build:
      context: .
      dockerfile: Apps/Identity.Admin/Dockerfile

  identityprovider:
    image: identityprovider
    build:
      context: .
      dockerfile: Identity/IdentityProvider/Dockerfile

