<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-Provider-73432761-743c-43e4-afea-060721fdb913</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.5" NoWarn="NU1605" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="9.0.5" NoWarn="NU1605" />
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.5" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.5" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.5" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.5">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Identity.Web" Version="3.9.3" />
        <PackageReference Include="Microsoft.Identity.Web.UI" Version="3.9.3" />
        <PackageReference Include="Microsoft.Identity.Web.DownstreamApi" Version="3.9.3" />
        <PackageReference Include="NSwag.AspNetCore" Version="14.4.0" />
        <PackageReference Include="NSwag.CodeGeneration.CSharp" Version="14.4.0" />
        <PackageReference Include="NSwag.CodeGeneration.TypeScript" Version="14.4.0" />
        <PackageReference Include="NSwag.Generation.AspNetCore" Version="14.4.0" />
        <PackageReference Include="OpenIddict.AspNetCore" Version="6.3.0" />
        <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="6.3.0" />
        <PackageReference Include="OpenIddict.Quartz" Version="6.3.0" />
        <PackageReference Include="PasswordGenerator" Version="2.1.0" />
        <PackageReference Include="Proggmatic.SpaServices.Vite" Version="9.0.1" />
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Apps\Client.Infrastructure\Client.Infrastructure.csproj" />
      <ProjectReference Include="..\..\Framework\Identity.Shared\Identity.Shared.csproj" />
      <ProjectReference Include="..\Identity.Core\Identity.Core.csproj" />
      <ProjectReference Include="..\Identity.Infrastructure\Identity.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Files\" />
    </ItemGroup>

</Project>
