<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
      <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="9.0.4" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.4" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.4" />
      <PackageReference Include="NSwag.MSBuild" Version="14.4.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.9.0" />
    </ItemGroup>
    <Target Name="NSwag">
        <Exec WorkingDirectory="$(ProjectDir)\Api" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development" Command="$(NSwagExe_Net80) run ./nswag.json /variables:Configuration=$(Configuration)" />
    </Target>

</Project>
