<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="9.0.6" />
      <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.6" />
      <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.6" />
      <PackageReference Include="NSwag.MSBuild" Version="14.4.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.12.1" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Configurations\" />
      <Folder Include="Models\" />
      <Folder Include="Services\Resource_1\" />
      <Folder Include="Services\Resource_2\" />
      <Folder Include="Services\Resource_3\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Framework\Identity.Shared\Identity.Shared.csproj" />
    </ItemGroup>
    <Target Name="NSwag">
        <Exec WorkingDirectory="$(ProjectDir)\Api" EnvironmentVariables="ASPNETCORE_ENVIRONMENT=Development" Command="$(NSwagExe_Net80) run ./nswag.json /variables:Configuration=$(Configuration)" />
    </Target>

</Project>
