<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-WebApp.Razor-f7b0cc13-d5c7-415b-b7a0-82554c8c9c23</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.5" NoWarn="NU1605" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="9.0.5" NoWarn="NU1605" />
        <PackageReference Include="Microsoft.Identity.Web" Version="3.9.3" />
        <PackageReference Include="Microsoft.Identity.Web.DownstreamApi" Version="3.9.3" />
        <PackageReference Include="Microsoft.Identity.Web.UI" Version="3.9.3" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.12.0" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>
